Book/Book/urls.py
from django.contrib import admin
from django.urls import path, include
from enroll import views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),
    path('show', views.show),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', views.loginpage, name='loginpage'),
    path('register/', views.register, name='register'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

Book/enroll/models.py
from django.db import models
import datetime
# Create your models here.


class ManageBook (models.Model):
    Authorname = models.CharField(max_length=100)
    Booktitle = models.CharField(max_length=100)
    Imprint = models.CharField(max_length=50)
    Publicationdate = models.DateField()

    class Meta:
        db_table = "managebook"

Book/enroll/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from .models import ManageBook
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ManagebookForm (forms.ModelForm):
    class Meta:
        model = ManageBook
        fields = "__all__"


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email')

Book/enroll/views.py
from django import forms
from django.shortcuts import render, redirect
from .forms import ManagebookForm
from .models import ManageBook
from django.contrib.auth import authenticate, login
from .forms import CreateUserForm
from django.contrib import messages
# Create your views here.


def emp(request):
    if request.method == "POST":
        form = ManagebookForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
                # return redirect('/')

            except:
                pass
    else:
        form = ManagebookForm()
    return render(request, 'index.html', {'form': form})


def show(request):
    context = {'show': ManageBook.objects.all()}
    return render(request, "show.html", context)


def edit(request, id):
    book = ManageBook.objects.get(pk=id)
    return render(request, 'edit.html', {'book': book})


def update(request, id):
    book = ManageBook.objects.get(pk=id)
    form = ManagebookForm(request.POST, instance=book)
    if form.is_valid:
        form.save()
        return redirect("/show")
        # return redirect('/')
    return render(request, 'edit.html', {'book': book})


def destroy(request, id):
    book = ManageBook.objects.get(pk=id)
    book.delete()
    return redirect("/show")
    # return redirect('/')


def loginpage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/show')
        else:
            messages.info(request, 'Username OR Password is incorrect')
            return render(request, "auth/login.html")

    context = {}
    return render(request, "auth/login.html", context)


def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            return redirect('loginpage')
    context = {'form': form}
    return render(request, "auth/register.html", context)

Book/enroll/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/style.css">
</head>

<body>
    {% block content %}
    {% endblock content %}

</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

</html>

Book/enroll/templates/edit.html
{% extends "base.html" %}
{% block content %}
<form method="POST" class="post-form" action="/update/{{book.id}}">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Update Details</h3>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Authorname:</label>
            <div class="col-sm-4">
                <input type="text" name="Authorname" id="id_Authorname" required maxlength="50"
                    value="{{ book.Authorname }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Booktitle:</label>
            <div class="col-sm-4">
                <input type="text" name="Booktitle" id="id_Booktitle" required maxlength="100"
                    value="{{ book.Booktitle }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label"> Imprint:</label>
            <div class="col-sm-4">
                <input type="text" name="Imprint" id="id_Imprint" required maxlength="254" value="{{ book.Imprint }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Publicationdate:</label>
            <div class="col-sm-4">
                <input type="text" name="Publicationdate" id="id_Publicationdate" required maxlength="15"
                    value="{{ book.Publicationdate }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>
    </div>
</form>
{% endblock content %}

Book/enroll/templates/home.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Book</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
            <div>
                <a href="{% url 'logout' %}" class="ml-2 mr-2">Log Out</a>
            </div>
        </div>
        <span class="hello-msg">Hello , {{request.user}}</span>
    </nav>
</div>
</div>

{% else %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Book</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
            <div>
                <a href="{% url 'loginpage' %}">Log in</a>
            </div>
        </div>
    </nav>
</div>
</div>
{% endif %}
{% endblock %}

Book/enroll/templates/index.html
{% extends "base.html" %}
{% block content %}
<form method="POST" class="post-form" action="/emp">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Enter Details</h3>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Authorname:</label>
            <div class="col-sm-4">
                {{ form.Authorname }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Booktitle:</label>
            <div class="col-sm-4">
                {{ form.Booktitle }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Imprint:</label>
            <div class="col-sm-4">
                {{ form.Imprint }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Publicationdate:</label>
            <div class="col-sm-4">
                {{ form.Publicationdate }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</form>
{% endblock content %}

Book/enroll/templates/show.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Book</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
            <div>
                <a href="{% url 'logout' %}" class="ml-2 mr-2">Log Out</a>
            </div>
        </div>
        <span class="hello-msg">Hello , {{request.user}}</span>
    </nav>
    <table class="table table-striped table-bordered table-sm">
        <thead class="thead-dark">
            <tr>
                <th>Authorname</th>
                <th>Booktitle</th>
                <th>Imprint</th>
                <th>Publicationdate</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for showbook in show %}
            <tr>
                <td>{{ showbook.Authorname }}</td>
                <td>{{ showbook.Booktitle }}</td>
                <td>{{ showbook.Imprint }}</td>
                <td>{{ showbook.Publicationdate }}</td>
                <td>
                    <a href="/edit/{{ showbook.id }}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
                    <a href="/delete/{{ showbook.id }}">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<br>
<br>
<center><a href="/emp" class="btn btn-primary">Add to books</a></center>
{% endblock content %}